#!/bin/bash

# ExpatGuide Internal Articles Index Generator
# 扫描 src/content/docs/vietnam/ 下所有文章, 生成 Research/internal-articles-index.md
# 用法: bash generate-link-index.sh
# 兼容 macOS 默认 bash 3.2

DOCS_DIR="src/content/docs"
OUTPUT="Research/internal-articles-index.md"

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

# 检查是否在项目根目录
if [ ! -d "$DOCS_DIR" ]; then
  echo "错误: 找不到 $DOCS_DIR 目录。请在项目根目录运行此脚本。"
  exit 1
fi

# 确保 Research 目录存在
mkdir -p Research

# 临时文件按分类存储
TMP_DIR=$(mktemp -d)
trap "rm -rf $TMP_DIR" EXIT

# 写入文件头
cat > "$OUTPUT" <<EOF
# ExpatGuide Internal Articles Index

Auto-generated by \`generate-link-index.sh\`. Do not edit manually.
Last updated: $(date "+%Y-%m-%d %H:%M:%S")

This file is the single source of truth for "which articles exist on the site."
When running SOP prompts, paste the list below into the AVAILABLE INTERNAL ARTICLES field.

Format: \`- /slug/path — one-line description from frontmatter\`

---

## Available Articles

EOF

# 计数
count=0

# 找到所有文章文件,排除 example.md 和 index 文件
FILES=$(find "$DOCS_DIR/vietnam" -name "*.md" -o -name "*.mdx" 2>/dev/null | grep -v "example.md" | sort)

for file in $FILES; do
  # 提取 slug 路径
  slug=$(echo "$file" | sed "s|^${DOCS_DIR}||" | sed 's|\.md$||' | sed 's|\.mdx$||')
  
  # 提取 frontmatter 的 description
  description=$(awk '
    /^---$/ { if (in_fm) exit; in_fm=1; next }
    in_fm && /^description:/ {
      sub(/^description:[[:space:]]*/, "")
      gsub(/^"|"$/, "")
      gsub(/^'\''|'\''$/, "")
      print
      exit
    }
  ' "$file")
  
  # 如果 description 为空,尝试从 title 字段提取
  if [ -z "$description" ]; then
    description=$(awk '
      /^---$/ { if (in_fm) exit; in_fm=1; next }
      in_fm && /^title:/ {
        sub(/^title:[[:space:]]*/, "")
        gsub(/^"|"$/, "")
        gsub(/^'\''|'\''$/, "")
        print
        exit
      }
    ' "$file")
  fi
  
  # 如果还是没有,用 slug 最后一段当描述
  if [ -z "$description" ]; then
    description=$(basename "$slug" | sed 's/-/ /g')
  fi
  
  # 从 slug 提取分类
  category=$(echo "$slug" | awk -F'/' '{print $3}')
  if [ -z "$category" ]; then
    category="other"
  fi
  
  # 写入对应分类的临时文件
  echo "- \`$slug\` — $description" >> "$TMP_DIR/$category"
  
  count=$((count + 1))
done

# 按预定义顺序输出分类
CATEGORY_ORDER="visa housing banking healthcare daily-life digital-nomad"

for category in $CATEGORY_ORDER; do
  if [ -f "$TMP_DIR/$category" ]; then
    # 首字母大写作为标题
    category_title=$(echo "$category" | awk '{print toupper(substr($0,1,1)) substr($0,2)}' | sed 's/-/ /g')
    # 将 category_title 中每个单词首字母大写
    category_title=$(echo "$category_title" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print}')
    
    echo "### $category_title" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    cat "$TMP_DIR/$category" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
  fi
done

# 处理未在预定义列表中的分类
for tmpfile in "$TMP_DIR"/*; do
  if [ -f "$tmpfile" ]; then
    category=$(basename "$tmpfile")
    # 检查是否已处理过
    is_known=false
    for known in $CATEGORY_ORDER; do
      if [ "$category" = "$known" ]; then
        is_known=true
        break
      fi
    done
    
    if [ "$is_known" = false ]; then
      category_title=$(echo "$category" | awk '{print toupper(substr($0,1,1)) substr($0,2)}' | sed 's/-/ /g')
      category_title=$(echo "$category_title" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print}')
      
      echo "### $category_title" >> "$OUTPUT"
      echo "" >> "$OUTPUT"
      cat "$tmpfile" >> "$OUTPUT"
      echo "" >> "$OUTPUT"
    fi
  fi
done

# 文件尾
cat >> "$OUTPUT" <<EOF
---

## Usage Notes

- **For GPT prompts**: Copy everything under "## Available Articles" (from the first \`###\` heading to the end of the last list) and paste into the \`AVAILABLE INTERNAL ARTICLES\` field of Prompts 1, 2, 4, 5, and the Deep Draft Prompt.
- **For ChatGPT project knowledge**: Upload this entire file to your ExpatGuide project. Replace the old version each time you regenerate.
- **After publishing new articles**: Re-run \`bash generate-link-index.sh\` to refresh this index, then re-upload to ChatGPT.

Total articles indexed: $count
EOF

echo ""
echo -e "${GREEN}✓${NC} Generated $OUTPUT"
echo -e "  ${CYAN}Indexed $count articles${NC}"
echo ""
echo "Next steps:"
echo "  1. Review $OUTPUT to confirm descriptions look good"
echo "  2. Upload this file to your ExpatGuide ChatGPT project (replace old version)"
echo "  3. Commit to git: git add $OUTPUT && git commit -m 'refresh internal articles index'"
echo ""
